// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPc8QqkH9Br0NY9pn_hpFRteXf0s0zKPk',
    appId: '1:727266902680:android:9f77a7f2f626e603cf86ed',
    messagingSenderId: '727266902680',
    projectId: 'nu-capstone-db',
    databaseURL: 'https://nu-capstone-db-default-rtdb.firebaseio.com',
    storageBucket: 'nu-capstone-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlOYkbj7FxVAwMS7JeMChN5sKXiJtEvM',
    appId: '1:727266902680:ios:1c585541a3ab7511cf86ed',
    messagingSenderId: '727266902680',
    projectId: 'nu-capstone-db',
    databaseURL: 'https://nu-capstone-db-default-rtdb.firebaseio.com',
    storageBucket: 'nu-capstone-db.appspot.com',
    iosClientId: '727266902680-csun26dcpek7hdgnhocfd3o37fb0rgn9.apps.googleusercontent.com',
    iosBundleId: 'com.johnduval',
  );
}
